name: flutter_recipe

description: "Simple way to find Tasty Recipe"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.14
  freezed: ^2.5.7
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
